cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),

]

o_store/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('product-list/', views.product_list, name='product_list'),
    path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_products(self):
        return Product.objects.filter(category=self)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class ProductType(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'ProductType'
        verbose_name_plural = 'ProductTypes'

    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, related_name='type', on_delete=models.PROTECT, blank=True, null=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.PROTECT)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True, null=True)
    description_ru = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(blank=True, default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    pixels = models.FloatField(blank=True, null=True)

    class Meta:
        ordering = ('created', 'name')
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart

from .forms import CartAddProductForm
from cart.forms import CartAddProductForm


# Create your views here.

@require_POST
def cart_add(request, product_id):
    """
    maxsulotni savatga qoshish va yangilash uchun korinish qismi
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})

main/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'main/index.html')

orders/views.py
import order
from django.conf.global_settings import SESSION_EXPIRE_AT_BROWSER_CLOSE
from django.shortcuts import render

import cart
from .tasks import order_created
# Create your views here.
# очистка корзины
if SESSION_EXPIRE_AT_BROWSER_CLOSE:

    cart.clear()
# запуск асинхронной задачи
order_created.delay(order.id)

shop/views.py
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
# Create your views here.
from .models import Category, Product, ProductType


def product_list(request, category_slug=None):
    category = None
    product_types = ProductType.objects.all()
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'shop/shop.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'product_types': product_types,
                   })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,

                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    products = Product.objects.filter(available=True)
    return render(request, 'shop/shop-single.html', {'product': product,
                                                     'cart_product_form': cart_product_form,
                                                     'products': products, }
                  )

templates/cart/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Shoppers &mdash; Colorlib e-Commerce Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                        <form action="" class="site-block-top-search">
                            <!--  <span class="icon icon-search2"></span>
                              <input type="text" class="form-control border-0" placeholder="Search">-->
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a href="{% url 'main:index' %}" class="js-logo-clone">id - cam</a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>

                                <li>
                                    <a href="{% url 'cart:cart_detail' %}" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count">{% with total_items=cart|length %}
                                            {% if cart|length > 0 %}
                                                {{ total_items }}
                                                <a href="{% url "cart:cart_detail" %}">

                </a>
                                            {% else %}

                                            {% endif %}
                                        {% endwith %}</span>
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <!-- <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">
                    <li class="has-children">
                        <a href= >Home</a>
                        <ul class="dropdown">
                            <li><a href="#">Menu One</a></li>
                            <li><a href="#">Menu Two</a></li>
                            <li><a href="#">Menu Three</a></li>
                            <li class="has-children">
                                <a href="#">Sub Menu</a>
                                <ul class="dropdown">
                                    <li><a href="#">Menu One</a></li>
                                    <li><a href="#">Menu Two</a></li>
                                    <li><a href="#">Menu Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="about.html">About</a>
                        <ul class="dropdown">
                            <li><a href="#">Menu One</a></li>
                            <li><a href="#">Menu Two</a></li>
                            <li><a href="#">Menu Three</a></li>
                        </ul>
                    </li>
                    <li><a href="../shop/shop.html">Shop</a></li>
                    <li><a href="#">Catalogue</a></li>
                    <li><a href="#">New Arrivals</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </div>-->
        </nav>
    </header>

    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0"><a href="{% url 'shop:product_list' %}">Do'kon</a> <span
                        class="mx-2 mb-0">/</span> <strong
                        class="text-black">Savat</strong></div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row mb-5">
                <form class="col-md-12" method="post">
                    <div class="site-blocks-table">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="product-thumbnail">Rasm</th>
                                <th class="product-name">Maxsulot</th>
                                <th class="product-price">Narx</th>
                                <th class="product-quantity">Soni</th>
                                <th class="product-total">Umumiy</th>
                                <th class="product-remove">O'chirish</th>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>    <!-- karzinkada maxsulotlani gorinishi -->
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                            <td class="product-thumbnail">
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img style="height: 60px" src="{% if product.image %}
                                    {{ product.image.url }}

                                {% endif %}">
                                                </a>
                                            </td>
                                            <td class="product-name">
                                                <h2 class="h5 text-black">{{ product.name }}</h2>
                                            </td>

                                            <td>{{ item.price }} 000 sum</td>
                                            <div class="input-group mb-3" style="max-width: 120px;">
                                                <td>{{ item.quantity }}</td>
                                            </div>

                                            <td class="num">{{ item.total_price }} 000 sum</td>

                                            <td><a class="btn btn-primary btn-sm"
                                                   href="{% url "cart:cart_remove" product.id %} ">O'chirish</a>
                                            </td>

                                        </tr>
                                    {% endwith %}
                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </form>
            </div>

            <div class="row">
                <div class="col-md-6">


                </div>
                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-7">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">Umumiy hisob</h3>
                                </div>
                            </div>
                            <div class="row mb-3">


                            </div>
                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">Total</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">{{ cart.get_total_price }} 000 sum</strong>
                                    <!-- total summa-->
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                   <!-- <button class="btn btn-primary btn-lg py-3 btn-block"
                                            onclick="window.location='checkout.html'">Adminga jonatish
                                    </button>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="site-footer border-top">
        <div class="container">

            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>

                        Copyright &copy;<script data-cfasync="false"
                                                src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                        <script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i>
                        by <a target="_blank" class="text-primary">Zuxriddin</a>

                    </p>
                </div>

            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/shop/shop-single.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ product.name }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                        <form action="" class="site-block-top-search">
                            <!--<span class="icon icon-search2"></span>
                            <input type="text" class="form-control border-0" placeholder="Search">-->
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a href="{% url 'main:index' %}" class="js-logo-clone">ID - C A M </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>

                                <li>
                                    <a href="{% url 'cart:cart_detail' %}" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count">{% with total_items=cart|length %}
                                            {% if cart|length > 0 %}
                                                {{ total_items }}
                                                <a href="{% url "cart:cart_detail" %}">

                </a>
                                            {% else %}

                                            {% endif %}
                                        {% endwith %}</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <!--  <ul class="site-menu js-clone-nav d-none d-md-block">
                    <li class="has-children">
                        <a>Home</a>
                        <ul class="dropdown">
                            <li><a href="#">Menu One</a></li>
                            <li><a href="#">Menu Two</a></li>
                            <li><a href="#">Menu Three</a></li>
                             <li class="has-children">
                             <a href="#">Sub Menu</a>
                             <ul class="dropdown">
                               <li><a href="#">Menu One</a></li>
                               <li><a href="#">Menu Two</a></li>
                               <li><a href="#">Menu Three</a></li>
                             </ul>
                           </li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a>About</a>
                        <ul class="dropdown">
                            <li><a href="#">Menu One</a></li>
                            <li><a href="#">Menu Two</a></li>
                            <li><a href="#">Menu Three</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="{% url 'shop:product_list' %}">Shop</a></li>
                    <li><a>Catalogue</a></li>
                    <li><a>New Arrivals</a></li>

                </ul>-->
            </div>
        </nav>
    </header>

    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0"><a href="{% url 'shop:product_list' %}">Home</a> <span
                        class="mx-2 mb-0">/</span> <strong
                        class="text-black">{{ product.name }}</strong></div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="



                            {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"
                         alt="Image" class="img-fluid">
                </div>
                <div class="col-md-6">
                    <h2 class="text-black">{{ product.name }}</h2>
                    <p>{{ product.description_ru }}</p>

                    <p><strong class="text-primary h4">{{ product.price }} 000 sum</strong></p>

                    <div class="mb-5">


                    </div>
                    <p>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input type="submit" value="Savatga">
                    </form>
                    </p>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section block-3 site-blocks-2 bg-light">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 site-section-heading text-center pt-4">
                    <h2>Yangi maxsulotlar</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="nonloop-block-3 owl-carousel">


                        {% for product in products %}
                            <div style="max-font-size: 60px" class="item">
                                <div class="block-4 text-center">
                                    <figure class="block-4-image">
                                        <img src="{{ product.image.url }}" alt="Image placeholder" class="img-fluid">
                                    </figure>
                                    <div class="block-4-text p-4">
                                        <h3><a href="#">{{ product.name }}</a></h3>
                                        <p class="mb-0">Eng sifatli xizmat</p>
                                        <p class="text-primary font-weight-bold">{{ product.price}} 000 sum</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="site-footer border-top">
        <div class="container">

            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>

                        Copyright &copy;<script data-cfasync="false"
                                                src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                        <script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i>
                        by <a target="_blank" class="text-primary">Zuxriddin</a>

                    </p>
                </div>

            </div>
        </div>
    </footer>

</div>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>
</html>